---
- name: Create Backend Directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Extract artifact.tar.gz to EC2 
  unarchive:
    src: artifact.tar.gz
    dest: /home/ubuntu/backend

# - name: "install npm"
#   become: true
#   apt:
#     name: npm
#     state: latest
#     update_cache: yes

- name: "executing node app with PM2"
  become: true
  shell: |
    cd /home/ubuntu/backend-app/dist
    pm2 stop default
    pm2 start -f main.js
  register: execute_node

- name: "print message"
  debug:
    msg: "{{execute_node.stdout_lines}}"

- name: "configure pm2 start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save